apiVersion: v1
kind: Secret
metadata:
  name: temporal-auth-secrets
stringData:
  issuer_url: https://YOUR_OKTA_DOMAIN/oauth2/default
  client_id:  (from your Okta app)
  client_secret:  (from your Okta app)